// Constellation stick figures for the sky tracker — Cherishvale's own lines,
// drawn only between stars already in stars.js (no external line catalogue).
// Each line is a pair of star names; the label is placed at the mean position.
var CONSTELLATIONS = [
  { n: "Orion", lines: [["Betelgeuse","Bellatrix"],["Bellatrix","Mintaka"],
      ["Mintaka","Alnilam"],["Alnilam","Alnitak"],["Alnitak","Saiph"],
      ["Saiph","Rigel"],["Rigel","Mintaka"],["Betelgeuse","Alnitak"]] },
  { n: "Ursa Major", lines: [["Dubhe","Merak"],["Merak","Phecda"],
      ["Phecda","Alioth"],["Alioth","Mizar"],["Mizar","Alkaid"],["Dubhe","Alioth"]] },
  { n: "Cassiopeia", lines: [["Caph","Schedar"],["Schedar","Ruchbah"]] },
  { n: "Crux", lines: [["Acrux","Gacrux"],["Mimosa","Alsephina"]] },
  { n: "Scorpius", lines: [["Dschubba","Antares"],["Antares","Sargas"],
      ["Sargas","Shaula"],["Shaula","Lesath"]] },
  { n: "Canis Major", lines: [["Sirius","Mirzam"],["Mirzam","Wezen"],
      ["Wezen","Adhara"],["Adhara","Aludra"],["Wezen","Aludra"]] },
  { n: "Canis Minor", lines: [["Procyon","Gomeisa"]] },
  { n: "Leo", lines: [["Regulus","Algieba"],["Algieba","Denebola"],["Denebola","Regulus"]] },
  { n: "Gemini", lines: [["Castor","Pollux"],["Pollux","Alhena"]] },
  { n: "Taurus", lines: [["Aldebaran","Elnath"]] },
  { n: "Auriga", lines: [["Capella","Menkalinan"],["Menkalinan","Elnath"]] },
  { n: "Pegasus", lines: [["Markab","Scheat"],["Scheat","Alpheratz"],
      ["Alpheratz","Algenib"],["Algenib","Markab"]] },
  { n: "Andromeda", lines: [["Alpheratz","Mirach"],["Mirach","Almach"]] },
  { n: "Perseus", lines: [["Mirfak","Algol"]] },
  { n: "Aquila", lines: [["Altair","Tarazed"]] },
  { n: "Bootes", lines: [["Arcturus","Izar"]] },
  { n: "Virgo", lines: [["Spica","Vindemiatrix"]] },
  { n: "Libra", lines: [["Zubenelgenubi","Zubeneschamali"]] },
  { n: "Sagittarius", lines: [["Kaus Australis","Kaus Media"],
      ["Kaus Media","Nunki"],["Nunki","Ascella"]] },
  { n: "Capricornus", lines: [["Deneb Algedi","Dabih"],["Dabih","Albaldah"]] },
  { n: "Cancer", lines: [["Asellus Borealis","Asellus Australis"],
      ["Asellus Australis","Acubens"]] },
  { n: "Aquarius", lines: [["Sadalsuud","Sadalmelik"]] },
  { n: "Draco", lines: [["Eltanin","Grumium"],["Grumium","Thuban"]] }
];
