// Generated by tools/build_ozone.py from NASA GIBS (public domain).
// Total-column ozone overlay for Earth; value in Dobson Units.
var OZONE = {"date": "2024-10-01", "layer": "OMI_Ozone_DOAS_Total_Column", "source": "NASA GIBS / OMI-Ozone DOAS (public domain)", "unit": "Dobson Units (DU)", "range": [220, 450], "img": "assets/earth/ozone.png"};
